### ISSUE TITLE
Can't build on Ubuntu 24.04

### ISSUE THREAD

**Issue by sem-hub** [seriyps/mtproto_proxy#113]
Well, may be it's easy to fix, but I don't know how to.
$ make
./rebar3 as prod release
=ERROR REPORT==== 20-Feb-2026::21:43:26.332158 ===
beam/beam_load.c(438): Error loading function rebar_dir:do_make_relative_path/2: op i_bif2: ssjbd:
  import 20 not a BIF

=ERROR REPORT==== 20-Feb-2026::21:43:26.335565 ===
beam/beam_load.c(184): Error loading module rebar_log:
  This BEAM file was compiled for a later version of the runtime system than the current (Erlang/OTP 25).
  To fix this, please re-compile this module with an Erlang/OTP 25 compiler.
  (Use of opcode 182; this emulator supports only up to 180.)

=ERROR REPORT==== 20-Feb-2026::21:43:26.332171 ===
Loading of /home/sem33/github/mtproto_proxy/rebar3/rebar/ebin/rebar_dir.beam failed: badfile

=ERROR REPORT==== 20-Feb-2026::21:43:26.335573 ===
Loading of /home/sem33/github/mtproto_proxy/rebar3/rebar/ebin/rebar_log.beam failed: badfile

escript: exception error: undefined function rebar_log:crashdump/2
  in function  rebar3:handle_error/2 (/home/runner/work/rebar3/rebar3/apps/rebar/src/rebar3.erl, line 392)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [Makefile:11: all] Error 127
